# Generated by Django 3.2.25 on 2025-07-16 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="price",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
