# Generated by Django 3.2.25 on 2025-07-16 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_post_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="category",
            field=models.ManyToManyField(null=True, to="blog.Category"),
        ),
    ]
